ln -s ../../hotmath2/inmh/genericprealg.inmh .
ln -s ../../hotmath2/inmh/genericalg1.inmh .
ln -s ../../hotmath2/inmh/genericgeo.inmh .
ln -s ../../hotmath2/inmh/genericalg2.inmh .
ln -s ../../hotmath2/inmh/mini6and7gt.inmh .
ln -s ../../hotmath2/inmh/minialg1gt.inmh .
ln -s ../../hotmath2/inmh/minigeogt.inmh .
ln -s ../../hotmath2/inmh/minialg2gt.inmh .
ln -s ../../hotmath2/inmh/cmextras.inmh .
ln -s ../../hotmath2/inmh/cmextrasgeo.inmh .
ln -s ../../hotmath2/inmh/cmextrasalg2.inmh .
ln -s ../../hotmath2/inmh/cmextrasgeo-2.inmh .
ln -s ../../hotmath2/inmh/alg1ptests.inmh .
ln -s ../../hotmath2/inmh/alg2ptests.inmh .
ln -s ../../hotmath2/inmh/prealgptests.inmh .
ln -s ../../hotmath2/inmh/geoptests.inmh .
ln -s ../../hotmath2/inmh/placement.inmh .
